apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: c4xsiljyy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c4xsiljyy-go 
  name: c4xsiljyy-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: c4xsiljyy-go
    weight: 100 
